typography_spectrum: 0.057265956653282046
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25117402663454413
  lightness: 0.45658469828777015
  saturation: 0.03735154657624662
  rhythmicContrast: 0.4092834840994328
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3732346147298813
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c0d0b98-1c18-479d-9dcc-eda04029c83e.png
name: Cyberdale
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Cyberdale, LLC'
description: Computers Simplified.
purpose: []
