name: Cyberdale
favicon: null
layout_spectrum: 0.3732346147298813
typography_spectrum: 0.057265956653282046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25117402663454413
  lightness: 0.45658469828777015
  saturation: 0.03735154657624662
  rhythmicContrast: 0.4092834840994328
purpose: []
